apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}
  labels:
    app: {{.Values.appName}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
    spec:
      imagePullSecrets:
        - name: {{.Values.imagePullSecretName}}
      containers:
      - name: {{.Values.appName}}
        image: {{.Values.imageName}}
        ports:
          - containerPort: 80
        resources: {}
